sudo: false

language: bash

before_script:
  - echo "machine github.com login $GITHUB_USER password $GITHUB_TOKEN" >> ~/.netrc

script:
  - bash -x -e < <(curl -kL https://github.com/phuslu/goproxy/raw/master/assets/scripts/ci.sh)

addons:
  apt:
    packages:
      - p7zip-full

notifications:
  email:
    recipients:
      - phuslu@hotmail.com
    on_success: change
    on_failure: change
