sudo: false

language: bash

install:
  - wget https://github.com/phuslu/goproxy/raw/master/assets/scripts/ci.sh

script:
  - bash -e ci.sh

addons:
  apt:
    packages:
      - p7zip-full

notifications:
  email:
    recipients:
      - phuslu@hotmail.com
    on_success: change
    on_failure: change
