sudo: false

language: bash

script:
  - cd /tmp
  - bash -xe < <(curl -kL https://github.com/phuslu/goproxy/raw/master/assets/build/ci.sh)

branches:
  only:
    - master

addons:
  apt:
    packages:
      - p7zip-full
