[default]
log_level = 2
reject_nil_sni = false
daemon_stderr = "./goproxy-vps.log"

[[http2]]
listen = ":443"
server_name = ["example.org"]
proxy_fallback = "http://127.0.0.1:80"
client_auth_pem = """"""

[[https]]
listen = ":443"
server_name = ["proxy.example.org"]
proxy_fallback = "file:///var/www/html"
proxy_auth_method = "pam"

[[tls]]
server_name = ["demo.example.org"]
backend = "127.0.0.1:8443"
terminate = false

[http]
listen = ":8087"
parent_proxy = "https://example.org"
