[default]
log_level = 2
daemon_stderr = "./goproxy-vps.log"

[[http2]]
listen = ":443"
server_name = ["example.org"]
proxy_fallback = "http://127.0.0.1:80"
client_auth_pem = """"""

[[http2]]
listen = ":443"
server_name = ["proxy.example.org"]
proxy_fallback = "file:///var/www/html"
proxy_auth_method = "pam"

[http]
listen = ":8087"
parent_proxy = "https://example.org"
